# Generated by Django 5.0.3 on 2024-03-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tourney_name',
            field=models.CharField(max_length=256, verbose_name='Tournament Name'),
        ),
    ]
