# Generated by Django 5.0.3 on 2024-03-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tournament_active_alter_tournament_tourney_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_type', models.CharField(max_length=256, verbose_name='Type')),
            ],
        ),
    ]
