# Generated by Django 5.0.3 on 2024-03-05 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_division_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.CharField(max_length=256, verbose_name='Name')),
                ('div_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.division_type')),
                ('tourney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tournament')),
            ],
        ),
    ]
