# Generated by Django 5.0.3 on 2024-03-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='tourney',
            new_name='tournament',
        ),
    ]
