# Generated by Django 5.0.3 on 2024-03-05 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='loss_r2_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='R2 ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.outcome'),
        ),
        migrations.AlterField(
            model_name='match',
            name='r2_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='R2 ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_r2_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
