# Generated by Django 5.0.3 on 2024-03-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_match_location_alter_match_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
